/**
 * Regenerates Web/Verify/output/REPORT.md after a screens.spec.ts run.
 *
 * The verdict column is NOT computed. It is filled in by a reviewer who opens the
 * reference JPG and the captured PNG side by side (the Read tool renders both) and
 * judges layout, hierarchy, colour and spacing. Pixel diffing is meaningless here:
 * the references are iOS simulator screenshots at a different scale and aspect ratio.
 *
 * Verdicts already recorded in a previous REPORT.md are preserved, keyed by
 * screen|theme|viewport, so re-running the capture does not wipe review work.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  captureName,
  GRADED_VIEWPORT,
  LOCALE_SENSITIVE_SCREENS,
  referenceFor,
  SCREENS,
  THEMES,
  VIEWPORTS,
} from './screen-catalog';

const OUTPUT_DIR = fileURLToPath(new URL('../output/', import.meta.url));
const REPORT_PATH = join(OUTPUT_DIR, 'REPORT.md');
const PENDING = '⬜ not yet reviewed';

type Row = { verdict: string; notes: string };

function readExistingVerdicts(): Map<string, Row> {
  const map = new Map<string, Row>();
  if (!existsSync(REPORT_PATH)) return map;
  for (const line of readFileSync(REPORT_PATH, 'utf8').split('\n')) {
    if (!line.startsWith('| `')) continue;
    const cells = line.split('|').map((c) => c.trim());
    // | screen | theme | viewport | graded | reference | capture | verdict | notes |
    if (cells.length < 9) continue;
    const key = `${cells[1].replace(/`/g, '')}|${cells[2]}|${cells[3]}`;
    map.set(key, { verdict: cells[7], notes: cells[8] });
  }
  return map;
}

export default async function writeReport(): Promise<void> {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const previous = readExistingVerdicts();

  const lines: string[] = [
    '# Visual parity report',
    '',
    'Generated by `Web/Verify/parity/screens.spec.ts` (globalTeardown).',
    '',
    'Paths are relative to `Web/Verify/`. **Do not pixel-diff these** — the references are',
    'iOS simulator screenshots at a different scale and aspect ratio. The verdict column is',
    'filled in by a reviewer who opens both images and judges layout, hierarchy, colour and',
    'spacing. Anything short of 1:1 must also be recorded in `Web/Docs/PARITY-GAPS.md`.',
    '',
    '**Grading (DECISIONS.md R9, corrected):** the app renders as a centred **402px logical**',
    '**column** — the iPhone 17 Pro width. Parity is measured on that column at **±2px**, so',
    'only the `402x874` rows are graded. (390×844 was the original ruling and was wrong: the',
    'reference JPGs are 368×800, and 402/874 → 368 while 390/844 → 370. A ±2px criterion at',
    '390 would have mis-graded every screen by 12px.)',
    'The `1280x900` rows are captured because that is the real window size, but outside the',
    'column the layout is unconstrained — those rows are informational (background fill,',
    'centring, no clipping) and are **not** held to ±2px.',
    '_(R8 bullet 2 still says 1280×900 is primary and needs amending — tracked as OQ9 in',
    '`golden-vectors.json`.)_',
    '',
    'Verdict values: `✅ match` · `🟡 close — see notes` · `❌ differs` · `⬜ not yet reviewed`',
    '',
    '| Screen | Theme | Viewport | Graded | Reference (iOS) | Capture (web) | Verdict | Notes |',
    '|---|---|---|---|---|---|---|---|',
  ];

  let missing = 0;
  for (const screen of SCREENS) {
    for (const theme of THEMES) {
      for (const viewport of VIEWPORTS) {
        const file = captureName(screen, theme, viewport.label);
        const capturePath = join(OUTPUT_DIR, file);
        const exists = existsSync(capturePath);
        if (!exists) missing++;
        const ref = referenceFor(screen, theme);
        const key = `${screen}|${theme}|${viewport.label}`;
        const prev = previous.get(key);
        const verdict = prev?.verdict && prev.verdict !== PENDING ? prev.verdict : PENDING;
        const notes = prev?.notes ?? '';
        const localeWarn = LOCALE_SENSITIVE_SCREENS.has(screen) ? ' ⚠️locale' : '';
        const graded =
          (viewport.label === GRADED_VIEWPORT ? '**±2px**' : 'info') + localeWarn;
        lines.push(
          `| \`${screen}\` | ${theme} | ${viewport.label} | ${graded} | ${
            ref ? `\`${ref}\`` : '_none captured_'
          } | ${exists ? `\`output/${file}\`` : '**MISSING**'} | ${
            exists ? verdict : '❌ not captured'
          } | ${notes} |`,
        );
      }
    }
  }

  const total = SCREENS.length * THEMES.length * VIEWPORTS.length;
  lines.push(
    '',
    `**${total - missing}/${total} captures present.**`,
    '',
    '## Screens with no iOS reference image',
    '',
    'These were not captured on the simulator, so the visual verdict can only be judged',
    'against `GROUND-TRUTH.md` prose and the sibling screens, not against a picture.',
    '',
    ...SCREENS.filter((s) => referenceFor(s, 'light') === null).map((s) => `- \`${s}\``),
    '',
    '## Account fixtures used for capture (R27)',
    '',
    'Every screenshot scenario uses **one account per type** (Main / Emergency / Savings).',
    'That is deliberate: iOS does not enforce `isPrimarySavings` uniqueness and sorts accounts',
    'inconsistently between the Dashboard and Settings, so a capture with two same-type accounts',
    'could differ between runs for reasons on **their** side. Grading must not flake on iOS',
    'ordering rather than on ours.',
    '',
    '## ⚠️ Locale-sensitive screens — do not grade naively',
    '',
    ...[...LOCALE_SENSITIVE_SCREENS].map((s2) => `- \`${s2}\``),
    '',
    '`account-editor` renders two incompatible number formats simultaneously: Target Amount',
    'via `AmountFormatter` (`27,000 RON`, comma) and Current Balance via',
    '`TextField(format: .number)` (`2.365`, period — the device locale, `SettingsSheet.swift:55`).',
    'The stored value is `2365` in both cases. On a US-formats machine that field renders',
    '`2,365` instead, so a reference/capture mismatch there may be the grading machine, not the',
    'port. Pin the locale before judging, or exclude the field from the verdict and say so in',
    'the notes. `2.365` is dangerously *readable* as a plausible number — same hazard class as',
    'R24\u2019s `parseUserInput("9,000 RON") = 9.000`.',
    '',
    '## Dark mode',
    '',
    'Only `dashboard` has a dark iOS reference (`13-dashboard-dark.jpg`). Dark verdicts for',
    'every other screen are judged for internal consistency (contrast, pure-black background,',
    'accent legibility) rather than against a reference.',
    '',
  );

  writeFileSync(REPORT_PATH, lines.join('\n'), 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[parity] wrote ${REPORT_PATH} (${total - missing}/${total} captures present)`);
}
