/**
 * VISUAL CAPTURE — priority 4 in DECISIONS.md D6.
 *
 * Navigates every screen in GROUND-TRUTH.md in BOTH colour schemes and BOTH
 * viewports (402×874 — the graded parity column, and 1280×900 — the real window) and writes
 * PNGs to Web/Verify/output/<screen>-<theme>-<viewport>.png.
 *
 * Deliberately NOT using Playwright's toHaveScreenshot() baselines: the reference
 * images are iOS simulator screenshots at a different scale and aspect ratio, so a
 * pixel diff would be noise. The verdict is human-style judgement, recorded in
 * output/REPORT.md (regenerated by globalTeardown) by a reviewer who actually
 * opens both images.
 *
 * One capture failure does not abort the sweep — each screen is captured
 * defensively and failures are collected and reported at the end of the test.
 */
import { expect, test, type Page } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import {
  completeOnboarding,
  OUTPUT_DIR,
  stepAccounts,
  stepExpenses,
  stepIncome,
  stepName,
  stepSavings,
  stepSummary,
  stepWelcome,
  TID,
} from './flows';

import { captureName, THEMES, VIEWPORTS } from './screen-catalog';

for (const viewport of VIEWPORTS) {
  for (const theme of THEMES) {
    test.describe(`Visual capture — ${theme} @ ${viewport.label}`, () => {
      test.use({
        colorScheme: theme,
        viewport: { width: viewport.width, height: viewport.height },
      });

      test(`capture every screen (${theme}, ${viewport.label})`, async ({ page, request }) => {
        test.slow();
        mkdirSync(OUTPUT_DIR, { recursive: true });
        const failures: string[] = [];

        const shot = async (screen: string, prepare: () => Promise<void>) => {
          const file = join(OUTPUT_DIR, captureName(screen, theme, viewport.label));
          try {
            await prepare();
            await page.screenshot({ path: file, fullPage: true });
          } catch (e) {
            failures.push(`${screen}: ${(e as Error).message.split('\n')[0]}`);
          }
        };

        // ---- onboarding, walked in order ----
        await completeOnboarding(page, request, 'welcome');
        await shot('onboarding-welcome', async () => {
          await expect(page.getByTestId(TID.onbWelcome)).toBeVisible();
        });
        await shot('onboarding-name', async () => {
          await stepWelcome(page);
          await expect(page.getByTestId(TID.onbName)).toBeVisible();
        });
        await shot('onboarding-income', async () => {
          await stepName(page);
          await expect(page.getByTestId(TID.onbIncome)).toBeVisible();
        });
        await shot('onboarding-accounts', async () => {
          await stepIncome(page);
          await expect(page.getByTestId(TID.onbAccounts)).toBeVisible();
        });
        await shot('onboarding-expenses', async () => {
          await stepAccounts(page);
          await expect(page.getByTestId(TID.onbExpenses)).toBeVisible();
        });
        await shot('onboarding-savings', async () => {
          await stepExpenses(page);
          await expect(page.getByTestId(TID.onbSavings)).toBeVisible();
        });
        await shot('onboarding-summary', async () => {
          await stepSavings(page);
          await expect(page.getByTestId(TID.onbSummary)).toBeVisible();
        });

        // ---- main app ----
        await shot('dashboard', async () => {
          await stepSummary(page);
          await expect(page.getByTestId(TID.dashboard)).toBeVisible();
        });
        await shot('expenses', async () => {
          await page.getByTestId(TID.tabExpenses).click();
          await expect(page.getByTestId(TID.expensesScreen)).toBeVisible();
        });
        await shot('expenses-category-expanded', async () => {
          await page.getByTestId(TID.categoryRow('housing')).click();
        });
        await shot('add-expense-sheet', async () => {
          await page.getByTestId(TID.addExpenseButton).click();
          await expect(page.getByTestId(TID.addExpenseSheet)).toBeVisible();
        });
        await dismissSheet(page);
        await shot('manage-categories', async () => {
          await page.getByTestId(TID.expensesOverflowMenu).click();
          await page.getByRole('menuitem', { name: 'Manage Categories' }).click();
          await expect(page.getByTestId(TID.manageCategoriesSheet)).toBeVisible();
        });
        await shot('new-category-sheet', async () => {
          await page
            .getByTestId(TID.manageCategoriesSheet)
            .getByRole('button', { name: /^\+$|Add Category/ })
            .click();
          await expect(page.getByTestId(TID.newCategorySheet)).toBeVisible();
        });
        await dismissSheet(page);
        await dismissSheet(page);
        await shot('insights', async () => {
          await page.getByTestId(TID.tabInsights).click();
          await expect(page.getByTestId(TID.insightsScreen)).toBeVisible();
        });
        await shot('settings', async () => {
          await page.getByTestId(TID.tabDashboard).click();
          await page.getByTestId(TID.toolbarSettings).click();
          await expect(page.getByTestId(TID.settingsSheet)).toBeVisible();
        });
        // Split allocation mode — the ground-truth hole walked 2026-08-06.
        await shot('settings-split-fixed', async () => {
          await page.getByTestId(TID.settingsStrategySplit).click();
        });
        await shot('settings-split-percentage', async () => {
          await page.getByTestId(TID.settingsSplitModePercentage('emergency')).click();
          await page.getByTestId(TID.settingsSplitModePercentage('savings')).click();
        });
        await shot('account-editor', async () => {
          await page.getByTestId(TID.settingsStrategyPriority).click();
          await page.getByTestId(TID.settingsAccountRow('emergency')).click();
        });
        await dismissSheet(page);
        await shot('newmonth-step1', async () => {
          await page.getByTestId(TID.newMonthButton).click();
          await expect(page.getByTestId(TID.newMonthSheet)).toBeVisible();
        });
        await shot('newmonth-step2', async () => {
          await page.getByTestId(TID.nmNextButton).click();
        });
        await shot('newmonth-step3', async () => {
          await page.getByTestId(TID.nmNextButton).click();
          await expect(page.getByTestId(TID.nmPlanAvailable)).toBeVisible();
        });
        // Split-at-target plan (S27): the two-rows-named-Savings case.
        await shot('settings-split-at-target-plan', async () => {
          await dismissSheet(page);
          await page.getByTestId(TID.toolbarSettings).click();
          await page.getByTestId(TID.settingsStrategySplit).click();
          await page.getByTestId(TID.settingsSplitModePercentage('emergency')).click();
          await page.getByTestId(TID.settingsSplitModePercentage('savings')).click();
          await dismissSheet(page);
          await page.getByTestId(TID.newMonthButton).click();
          await page.getByTestId(TID.nmNextButton).click();
          await page.getByTestId(TID.nmBalanceField('emergency')).fill('27000');
          await page.getByTestId(TID.nmNextButton).click();
          await expect(page.getByTestId(TID.nmTransferList)).toBeVisible();
        });

        expect(
          failures,
          `Screens that could not be captured in ${theme}/${viewport.label}:\n  - ${failures.join('\n  - ')}`,
        ).toEqual([]);
      });
    });
  }
}

/** Close whatever sheet is on top: Cancel / Done / Close, else Escape. */
async function dismissSheet(page: Page): Promise<void> {
  for (const name of ['Cancel', 'Done', 'Close']) {
    const btn = page.getByRole('button', { name, exact: true }).last();
    if (await btn.isVisible().catch(() => false)) {
      await btn.click().catch(() => {});
      return;
    }
  }
  await page.keyboard.press('Escape').catch(() => {});
}
