import Foundation
import Testing
@testable import Domain

/// Tests for ExpenseEntry struct - validates amount calculations,
/// frequency conversions, and category helpers.
@Suite("ExpenseEntry Tests")
struct ExpenseEntryTests {

    // MARK: - Initialization

    @Suite("Initialization")
    struct InitializationTests {

        @Test("Full initializer sets all properties")
        func fullInitializer() {
            let id = UUID()
            let categoryId = ExpenseCategory.autoTransport.id
            let accountId = UUID()

            let expense = ExpenseEntry(
                id: id,
                name: "Gas",
                amount: 300,
                frequency: .monthly,
                icon: "car.fill",
                categoryId: categoryId,
                linkedAccountId: accountId,
                isEnabled: true,
                notes: "Regular gas"
            )

            #expect(expense.id == id)
            #expect(expense.name == "Gas")
            #expect(expense.amount == 300)
            #expect(expense.frequency == .monthly)
            #expect(expense.icon == "car.fill")
            #expect(expense.categoryId == categoryId)
            #expect(expense.linkedAccountId == accountId)
            #expect(expense.isEnabled == true)
            #expect(expense.notes == "Regular gas")
        }

        @Test("Convenience initializer sets defaults")
        func convenienceInitializer() {
            let expense = ExpenseEntry(
                name: "Food",
                amount: 1000,
                icon: "cart.fill"
            )

            #expect(expense.name == "Food")
            #expect(expense.amount == 1000)
            #expect(expense.icon == "cart.fill")
            #expect(expense.frequency == .monthly)
            #expect(expense.categoryId == nil)
            #expect(expense.linkedAccountId == nil)
            #expect(expense.isEnabled == true)
            #expect(expense.notes == nil)
        }

        @Test("Convenience initializer with account link")
        func convenienceInitializerWithAccount() {
            let accountId = UUID()
            let expense = ExpenseEntry(
                name: "Food",
                amount: 1000,
                icon: "cart.fill",
                linkedAccountId: accountId
            )

            #expect(expense.linkedAccountId == accountId)
        }

        @Test("ID is auto-generated when not provided")
        func autoGeneratedId() {
            let expense1 = ExpenseEntry(name: "A", amount: 100, icon: "star")
            let expense2 = ExpenseEntry(name: "B", amount: 200, icon: "star")

            #expect(expense1.id != expense2.id)
        }
    }

    // MARK: - Monthly Amount Calculation

    @Suite("Monthly Amount Calculation")
    struct MonthlyAmountTests {

        @Test("Monthly expense returns same amount")
        func monthlyReturnsSame() {
            let expense = ExpenseEntry(
                name: "Rent",
                amount: 1500,
                frequency: .monthly,
                icon: "house.fill"
            )
            #expect(expense.monthlyAmount == 1500)
        }

        @Test("Annual expense returns 1/12 of amount")
        func annualReturnsDivided() {
            let expense = ExpenseEntry(
                name: "Insurance",
                amount: 2400,
                frequency: .annual,
                icon: "shield.fill"
            )
            // Using approximate comparison due to Decimal division precision
            #expect(abs(expense.monthlyAmount - 200) < Decimal(string: "0.01")!)
        }

        @Test("Annual expense with non-divisible amount")
        func annualNonDivisible() {
            let expense = ExpenseEntry(
                name: "License",
                amount: 100,
                frequency: .annual,
                icon: "doc.fill"
            )
            let expected = Decimal(100) / 12
            #expect(expense.monthlyAmount == expected)
        }
    }

    // MARK: - Annual Amount Calculation

    @Suite("Annual Amount Calculation")
    struct AnnualAmountTests {

        @Test("Monthly expense returns x12 amount")
        func monthlyReturnsMultiplied() {
            let expense = ExpenseEntry(
                name: "Rent",
                amount: 1500,
                frequency: .monthly,
                icon: "house.fill"
            )
            #expect(expense.annualAmount == 18000)
        }

        @Test("Annual expense returns same amount")
        func annualReturnsSame() {
            let expense = ExpenseEntry(
                name: "Insurance",
                amount: 2400,
                frequency: .annual,
                icon: "shield.fill"
            )
            #expect(expense.annualAmount == 2400)
        }
    }

    // MARK: - Display Amount

    @Suite("Display Amount")
    struct DisplayAmountTests {

        @Test("Monthly expense displays monthly for monthly view")
        func monthlyViewMonthlyExpense() {
            let expense = ExpenseEntry(
                name: "Rent",
                amount: 1500,
                frequency: .monthly,
                icon: "house.fill"
            )
            #expect(expense.displayAmount(for: .monthly) == 1500)
        }

        @Test("Monthly expense displays annual for annual view")
        func annualViewMonthlyExpense() {
            let expense = ExpenseEntry(
                name: "Rent",
                amount: 1500,
                frequency: .monthly,
                icon: "house.fill"
            )
            #expect(expense.displayAmount(for: .annual) == 18000)
        }

        @Test("Annual expense displays monthly for monthly view")
        func monthlyViewAnnualExpense() {
            let expense = ExpenseEntry(
                name: "Insurance",
                amount: 2400,
                frequency: .annual,
                icon: "shield.fill"
            )
            // Using approximate comparison due to Decimal division precision
            #expect(abs(expense.displayAmount(for: .monthly) - 200) < Decimal(string: "0.01")!)
        }

        @Test("Annual expense displays annual for annual view")
        func annualViewAnnualExpense() {
            let expense = ExpenseEntry(
                name: "Insurance",
                amount: 2400,
                frequency: .annual,
                icon: "shield.fill"
            )
            #expect(expense.displayAmount(for: .annual) == 2400)
        }
    }

    // MARK: - Category Helpers

    @Suite("Category Helpers")
    struct CategoryHelperTests {

        @Test("category() returns nil when categoryId is nil")
        func categoryNilWhenIdNil() {
            let expense = ExpenseEntry(name: "Food", amount: 100, icon: "cart.fill")
            #expect(expense.category() == nil)
        }

        @Test("category() returns category for valid default ID")
        func categoryReturnsDefault() {
            let expense = ExpenseEntry(
                name: "Gas",
                amount: 300,
                frequency: .monthly,
                icon: "car.fill",
                categoryId: ExpenseCategory.autoTransport.id
            )
            let category = expense.category()
            #expect(category != nil)
            #expect(category?.name == "Auto/Transport")
        }

        @Test("category() returns nil for unknown category ID")
        func categoryNilForUnknown() {
            let expense = ExpenseEntry(
                name: "Custom",
                amount: 100,
                frequency: .monthly,
                icon: "star.fill",
                categoryId: UUID() // Unknown ID
            )
            #expect(expense.category() == nil)
        }
    }

    // MARK: - Equatable

    @Suite("Equatable")
    struct EquatableTests {

        @Test("Same expense is equal")
        func sameIsEqual() {
            let id = UUID()
            let expense1 = ExpenseEntry(
                id: id,
                name: "Food",
                amount: 1000,
                frequency: .monthly,
                icon: "cart.fill"
            )
            let expense2 = ExpenseEntry(
                id: id,
                name: "Food",
                amount: 1000,
                frequency: .monthly,
                icon: "cart.fill"
            )
            #expect(expense1 == expense2)
        }

        @Test("Different ID means not equal")
        func differentIdNotEqual() {
            let expense1 = ExpenseEntry(name: "Food", amount: 1000, icon: "cart.fill")
            let expense2 = ExpenseEntry(name: "Food", amount: 1000, icon: "cart.fill")
            #expect(expense1 != expense2)
        }

        @Test("Different amount means not equal")
        func differentAmountNotEqual() {
            let id = UUID()
            let expense1 = ExpenseEntry(
                id: id, name: "Food", amount: 1000,
                frequency: .monthly, icon: "cart.fill"
            )
            let expense2 = ExpenseEntry(
                id: id, name: "Food", amount: 2000,
                frequency: .monthly, icon: "cart.fill"
            )
            #expect(expense1 != expense2)
        }
    }

    // MARK: - Real-World Scenarios

    @Suite("Real-World Scenarios")
    struct RealWorldTests {

        @Test("Car loan monthly calculation")
        func carLoanMonthly() {
            // From Python script: CREDIT_AUTO_RATA_LUNARA = 2850 RON/month
            let carLoan = ExpenseEntry(
                name: "Car Loan",
                amount: 2850,
                frequency: .monthly,
                icon: "car.fill",
                categoryId: ExpenseCategory.autoTransport.id
            )

            #expect(carLoan.monthlyAmount == 2850)
            #expect(carLoan.annualAmount == 34200)
        }

        @Test("Annual insurance monthly equivalent")
        func annualInsuranceMonthly() {
            // Car insurance paid annually
            let insurance = ExpenseEntry(
                name: "Car Insurance",
                amount: 2500,
                frequency: .annual,
                icon: "shield.fill",
                categoryId: ExpenseCategory.autoTransport.id
            )

            let monthlyEquivalent = insurance.monthlyAmount
            // 2500 / 12 ≈ 208.33
            #expect(monthlyEquivalent > 208)
            #expect(monthlyEquivalent < 209)
        }

        @Test("Mixed expenses total calculation")
        func mixedExpensesTotal() {
            let expenses = [
                ExpenseEntry(name: "Rent", amount: 1500, frequency: .monthly, icon: "house.fill"),
                ExpenseEntry(name: "Food", amount: 3000, frequency: .monthly, icon: "cart.fill"),
                ExpenseEntry(name: "Insurance", amount: 2400, frequency: .annual, icon: "shield.fill")
            ]

            let totalMonthly = expenses.reduce(Decimal.zero) { $0 + $1.monthlyAmount }
            // 1500 + 3000 + 200 = 4700 (approximate due to Decimal division)
            #expect(abs(totalMonthly - 4700) < Decimal(string: "0.01")!)
        }

        @Test("Enabled filter")
        func enabledFilter() {
            let expenses = [
                ExpenseEntry(name: "Active", amount: 100, frequency: .monthly, icon: "star", isEnabled: true),
                ExpenseEntry(name: "Disabled", amount: 200, frequency: .monthly, icon: "star", isEnabled: false)
            ]

            let enabledTotal = expenses
                .filter { $0.isEnabled }
                .reduce(Decimal.zero) { $0 + $1.monthlyAmount }

            #expect(enabledTotal == 100)
        }
    }
}
